version.0.2

phases:
  install:
    runtime-version:
      java: corretto11
  prebuild:
    commands:
      - echo nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build sytarted on "date"
  postbuild:
    commands:
      - echo Build completed on "date"
  artifacts:
    files:
      -'**/*"
  
    
